# Тензоры

## От списков к тензорам

In [1]:
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

3.0

In [4]:
a

[1.0, 2.0, 3.0]

## Первые тензоры!

In [5]:
import torch

In [6]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0

In [10]:
a

tensor([1., 1., 2.])

### Тензор координат

In [11]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points[0] = torch.tensor([1, 2])

In [18]:
points

tensor([[1., 2.],
        [0., 0.],
        [0., 0.]])

In [19]:
points[0, 1]

tensor(2.)

In [20]:
points[0][1]

tensor(2.)

In [21]:
# Можно и так, и так обращаться к элементам

In [24]:
points[None]

tensor([[[1., 2.],
         [0., 0.],
         [0., 0.]]])

In [27]:
points.unsqueeze(0)

tensor([[[1., 2.],
         [0., 0.],
         [0., 0.]]])

In [25]:
points

tensor([[1., 2.],
        [0., 0.],
        [0., 0.]])

In [28]:
# unsqueeze увеличивает размерность тензора на 1. [None] делает тоже самое в действительности

### Тензоры поименованные

In [29]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([.2126, .7152, .0722])

In [30]:
batch_t = torch.randn(2, 3, 5, 5)

In [31]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [32]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)