# PyTorch learning by book

## Libraries

In [1]:
import torch

In [3]:
torch.__version__

'1.13.1'

# Chapter 1

## Tensors

In [6]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [7]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [8]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [12]:
torch.rand(1).item()

0.8418099284172058

In [15]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [16]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

AssertionError: Torch not compiled with CUDA enabled